project:
  type: website
  output-dir: docs

website:
  title: "Course Title"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/halieute/gis_course/
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials
      - href: https://halieute.github.io/gis_course/discussions
        text: Forum
    page-footer:
    left: |
     All contents are Â© Souleymane Maman Nouri Souley and licensed under
     [Creative Commons](https://creativecommons.org/licenses/by-sa/4.0/)
    right: |
     [{{< fa brands github >}} ](https://halieute.github.io/)

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

